import type { FunctionalSession } from './types'
import { FUNCTIONAL_CATEGORY } from './types'

// Programming principles shared by both sessions: these are not StrongLifts progression
// workouts. The aim is movement quality, not increasing load — see each session's
// `programmingNotes` for the guidance shown to the user before they start.
const SHARED_PROGRAMMING_NOTES = [
  'Not a StrongLifts progression session — the aim is movement quality, not increasing load.',
  'Keep 3–5 reps in reserve and never grind a rep. Use a weight that allows perfect control; if technique deteriorates, reduce the weight.',
  'For mobility work, progress means better range of motion, control and stability — not more weight or reps.',
]

const SESSION_DESCRIPTION =
  'Low-intensity accessory and mobility session designed to complement StrongLifts 5×5. Focus on movement quality, mobility, stability and core strength rather than fatigue or progression.'

export const FUNCTIONAL_SESSIONS: FunctionalSession[] = [
  {
    id: 'fm1',
    name: 'Functional / Maintenance 1',
    focus: 'Hips, lower body mobility, unilateral stability and core',
    category: FUNCTIONAL_CATEGORY,
    description: SESSION_DESCRIPTION,
    targetRPE: '5-6',
    targetDurationMinutes: [25, 30],
    programmingNotes: SHARED_PROGRAMMING_NOTES,
    exercises: [
      {
        id: 'hip-switches-90-90',
        name: '90/90 Hip Switches',
        section: 'warmup',
        sets: 1,
        prescription: '8 reps each side',
        cue: 'Slow and controlled.',
        equipment: [],
      },
      {
        id: 'cossack-squat',
        name: 'Cossack Squat',
        section: 'warmup',
        sets: 1,
        prescription: '5 reps each side',
        cue: 'Controlled depth.',
        equipment: [],
      },
      {
        id: 'bodyweight-squat-pry',
        name: 'Bodyweight Squat + Pry',
        section: 'warmup',
        sets: 1,
        prescription: '8 reps',
        cue: 'Pause in the bottom and gently move the knees side to side.',
        equipment: [],
      },
      {
        id: 'cat-cow',
        name: 'Cat-Cow',
        section: 'warmup',
        sets: 1,
        prescription: '6-8 reps',
        cue: 'Controlled spinal movement.',
        equipment: [],
      },
      {
        id: 'landmine-reverse-lunge',
        name: 'Landmine Reverse Lunge',
        section: 'main',
        sets: 3,
        prescription: '8 reps each leg',
        cue: 'Light/moderate weight. 2-3 second eccentric. RPE 5-6. Focus on hip, knee and ankle control.',
        equipment: ['Barbell', 'Landmine attachment'],
      },
      {
        id: 'single-leg-rdl',
        name: 'Single-Leg RDL',
        section: 'main',
        sets: 3,
        prescription: '8 reps each side',
        cue: 'Prefer kettlebell. Light/moderate weight, controlled movement. Focus on hamstrings, glutes, balance and hip stability.',
        equipment: ['Kettlebell'],
      },
      {
        id: 'ab-roller',
        name: 'Ab Roller',
        section: 'main',
        sets: 3,
        prescription: '6-10 reps',
        cue: 'Controlled. Stop before losing trunk/pelvic control — do not train to failure.',
        equipment: ['Ab roller'],
      },
      {
        id: 'half-kneeling-hip-flexor-stretch',
        name: 'Half-Kneeling Hip Flexor Stretch',
        section: 'cooldown',
        sets: 1,
        prescription: '45 seconds each side',
        equipment: [],
      },
      {
        id: 'hamstring-stretch',
        name: 'Hamstring Stretch',
        section: 'cooldown',
        sets: 1,
        prescription: '45 seconds each side',
        equipment: [],
      },
      {
        id: 'deep-squat-hold',
        name: 'Deep Squat Hold',
        section: 'cooldown',
        sets: 1,
        prescription: '60 seconds',
        cue: 'Comfortable depth.',
        equipment: [],
      },
    ],
  },
  {
    id: 'fm2',
    name: 'Functional / Maintenance 2',
    focus: 'Upper-back health, shoulder mobility, trunk rotation and posture',
    category: FUNCTIONAL_CATEGORY,
    description: SESSION_DESCRIPTION,
    targetRPE: '5-6',
    targetDurationMinutes: [25, 30],
    programmingNotes: SHARED_PROGRAMMING_NOTES,
    exercises: [
      {
        id: 'band-pull-aparts',
        name: 'Band Pull-Aparts',
        section: 'warmup',
        sets: 1,
        prescription: '15 reps',
        cue: 'Light resistance.',
        equipment: ['Resistance band'],
      },
      {
        id: 'thoracic-rotations',
        name: 'Thoracic Rotations',
        section: 'warmup',
        sets: 1,
        prescription: '6 reps each side',
        cue: 'Controlled.',
        equipment: [],
      },
      {
        id: 'scapular-push-ups',
        name: 'Scapular Push-Ups',
        section: 'warmup',
        sets: 1,
        prescription: '10 reps',
        cue: 'Controlled.',
        equipment: [],
      },
      {
        id: 'neck-rotations',
        name: 'Neck Rotations',
        section: 'warmup',
        sets: 1,
        prescription: '5 reps each direction',
        cue: 'Gentle range of motion.',
        equipment: [],
      },
      {
        id: 'single-arm-landmine-row',
        name: 'Single-Arm Landmine Row',
        section: 'main',
        sets: 3,
        prescription: '10 reps each side',
        cue: 'Moderate/light weight. Controlled eccentric with a brief squeeze at the top. RPE 5-6.',
        equipment: ['Barbell', 'Landmine attachment'],
      },
      {
        id: 'half-kneeling-landmine-press',
        name: 'Half-Kneeling Landmine Press',
        section: 'main',
        sets: 3,
        prescription: '8 reps each side',
        cue: "Light/moderate weight. RPE 5-6. Stay within the landmine's forward/upward arc — no overhead press or overhead clearance.",
        equipment: ['Barbell', 'Landmine attachment'],
      },
      {
        id: 'band-face-pull',
        name: 'Band Face Pull',
        section: 'main',
        sets: 3,
        prescription: '15 reps',
        cue: '2-3 sets. Light/moderate resistance, controlled. Focus on upper back/rear shoulder/scapular movement.',
        equipment: ['Resistance band'],
      },
      {
        id: 'landmine-rotation',
        name: 'Landmine Rotation',
        section: 'main',
        sets: 2,
        prescription: '8 reps each side',
        cue: 'Light weight, controlled rotation. A movement-quality/core exercise, not a conditioning exercise.',
        equipment: ['Barbell', 'Landmine attachment'],
      },
      {
        id: 'childs-pose',
        name: "Child's Pose",
        section: 'cooldown',
        sets: 1,
        prescription: '60 seconds',
        cue: 'Choose two cool-down stretches.',
        equipment: [],
        optional: true,
      },
      {
        id: 'thoracic-extension',
        name: 'Thoracic Extension',
        section: 'cooldown',
        sets: 1,
        prescription: '60 seconds',
        cue: 'Using a bench if appropriate. Choose two cool-down stretches.',
        equipment: [],
        optional: true,
      },
      {
        id: 'doorway-pec-stretch',
        name: 'Doorway Pec Stretch',
        section: 'cooldown',
        sets: 1,
        prescription: '45 seconds each side',
        cue: 'Choose two cool-down stretches.',
        equipment: [],
        optional: true,
      },
      {
        id: 'wrist-forearm-mobility',
        name: 'Wrist / Forearm Mobility',
        section: 'cooldown',
        sets: 1,
        prescription: '1-2 minutes',
        cue: 'Choose two cool-down stretches.',
        equipment: [],
        optional: true,
      },
    ],
  },
]

export function getFunctionalSession(id: string): FunctionalSession | undefined {
  return FUNCTIONAL_SESSIONS.find(s => s.id === id)
}
